# Generated by Django 4.1.7 on 2023-02-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_cheese_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.CharField(max_length=255)),
                ('reviewer', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('recommend', models.BooleanField()),
            ],
        ),
    ]
