# Generated by Django 4.1.7 on 2023-03-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='catalogue.cheese'),
        ),
    ]
