# Generated by Django 4.1.7 on 2023-03-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_customer_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
    ]
